services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
# sempre rodar este comando no terminal quando for fazer algum teste
# cd infra
# docker compose up -d
# cd ..
# npm run dev
